### ISSUE TITLE
Import inside IntlTelInput.js can not be parsed

### ISSUE THREAD

**Issue by thomasledoux1** [patw0929/react-intl-tel-input#341]
## Expected Behavior

We updated the module from version 6 to version 8, and we can not compile our component which includes this module anymore. 
Our Browserify is getting stuck on the import of libphonenumber-js-utils (https://github.com/patw0929/react-intl-tel-input/blob/d769a1e9a8b5b921b1f9bef74e8b6e75ceea7d73/src/components/IntlTelInput.js#L511)
Is there any chance you could rewrite this, so the import can be done at the top level, and will be transpiled (like the imports for React in this file)?

**Comment by mcataford** [comment]
Hi @thomasledoux1!

Thanks for reporting the issue! This specific import seems to have been there since ~v5, so it might be a red herring. :thinking: That being said, I'm already doing other work that would accomplish this (#348), so it'll definitely be done in the near future!

Could I take a peek at the output from Browserify? Since the dynamic import was there all along, something else must have changed. :thinking:

**Comment by thomasledoux1** [comment]
Hey @mcataford ,
The output from Browserify is the following:

Browserify error: { Error: Parsing file C:\Projects\**\src\Features\**\code\node_modules\react-intl-tel-input\dist\components\IntlTelInput.js: Unexpected token (322:12)
    at Deps.parseDeps (C:\Projects\**\src\Projects\Corporate\code\node_modules\module-deps\index.js:481:28)
    at getDeps (C:\Projects\**\src\Projects\Corporate\code\node_modules\module-deps\index.js:414:40)
    at C:\Projects\**\src\Projects\Corporate\code\node_modules\module-deps\index.js:398:32
    at ConcatStream.<anonymous> (C:\Projects\**\src\Projects\Corporate\code\node_modules\concat-stream\index.js:36:43)
    at ConcatStream.emit (events.js:194:15)
    at finishMaybe (C:\Projects\**\src\Projects\Corporate\code\node_modules\concat-stream\node_modules\readable-stream\lib\_stream_writable.js:475:14)
    at endWritable (C:\Projects\**\src\Projects\Corporate\code\node_modules\concat-stream\node_modules\readable-stream\lib\_stream_writable.js:485:3)
    at ConcatStream.Writable.end (C:\Projects\**\src\Projects\Corporate\code\node_modules\concat-stream\node_modules\readable-stream\lib\_stream_writable.js:455:41)
    at DuplexWrapper.onend (C:\Projects\**\src\Projects\Corporate\code\node_modules\readable-stream\lib\_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:277:13)
    at DuplexWrapper.emit (events.js:194:15)
    at endReadableNT (C:\Projects\**\src\Projects\Corporate\code\node_modules\readable-stream\lib\_stream_readable.js:1010:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  stream:
   Labeled {
     _readableState:
      ReadableState {
        objectMode: true,
        highWaterMark: 16,
        buffer: BufferList { length: 0 },
        length: 0,
        pipes: [Labeled],
        pipesCount: 1,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     _events:
      [Object: null prototype] {
        end: [Array],
        error: [Function],
        data: [Function: ondata],
        _mutate: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     _writableState:
      WritableState {
        objectMode: true,
        highWaterMark: 16,
        finalCalled: false,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [CorkedRequest] },
     writable: false,
     allowHalfOpen: true,
     _options: { objectMode: true },
     _wrapOptions: { objectMode: true },
     _streams: [ [Deps], [DestroyableTransform] ],
     length: 2,
     label: 'deps' } }

**Comment by mcataford** [comment]
Interesting!

I have a path forward to remove that import, but I'm doubtful that it's the root cause here. I'll try and set up Browserify to try it out first-hand and try to reproduce. If you have any insights about the circumstances I need to reproduce for the error to happen, I'd welcome the feedback!

**Comment by thomasledoux1** [comment]
Well I'm no expert in the whole build setup, that's in the hands of my colleague who's currently not working on this project. So I'm afraid I will not be able to help you out there..

**Comment by mcataford** [comment]
Sounds good, I'll play around with it and see what I can find!

**Comment by thomasledoux1** [comment]
Could you give me a shout if/when this is released? I'll happily test it in our project then!

**Comment by mcataford** [comment]
@thomasledoux1 Absolutely! I've locked down some time this week to play with Browserify, as soon as I get some clarity on it I'll update this thread. I've also got a way forward to remove that async import, so I'll test that too then. :rocket:

**Comment by korzhik123** [comment]
Hi, we have the same issue happening. 
migrated from V7.1.1 to the latest and seeing the error in jest saying that it couldn't parse import('libphonenumber-js-utils').

**Comment by korzhik123** [comment]
output from jest 

Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/oaitbekov/Projects/bizsignupnodeweb/node_modules/stakeholder/node_modules/react-intl-tel-input/dist/components/IntlTelInput.js:322
          import('libphonenumber-js-utils').then(function () {
          ^^^^^^

    SyntaxError: Unexpected token import
